<h1>Look at example curl request!</h1>
<p><?php echo $this->escapeHtml($description) ?>; </p>
<pre>
<?php echo $this->escapeHtml($exampleCode) ?>;
</pre>
<p>
    Response contains next information:
    invoiceDate, invoiceNumber, invoiceTotal, invoiceFreight
</p>
<p>For activation could you send your server IP Address to
    <a href="mailto:kwadro2010@gmail.com">
        kwadro2010@gmail.com
    </a>
</p>
