<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<div class="jumbotron">
    <h1 class="display-4">Welcome to<br>Parser Ups Invoice Application</h1>
    <hr class="my-4">
    <a class="btn btn-primary btn-lg" href="https://github.com/kwadro/ups-invoice/tree/release/1.0.0" target="_blank">
        Check Parser Ups Invoice on GitHub &raquo;
    </a>
</div>

<div class="card-deck">
    <div class="card">
        <h2 class="card-header">Ups Commercial Invoice</h2>
        <div class="card-body">
            <p>
                You can view the data in the UPS commercial invoice here.
                <a class="btn btn-primary" href="https://www.ups.com/media/en/Commercial_Invoice_Guide.pdf">Commercial invoice</a>,
            </p>
        </div>
    </div>

    <div class="card">
        <h2 class="card-header">Quick Start</h2>
        <div class="card-body">
            <p>
                Please review the quick start guide
            </p>

            <a class="btn btn-primary" href="<?= $this->url('guide-index') ?>" target="_blank">
                Guide &raquo;
            </a>
        </div>
    </div>
</div>
